"use client";
import { useState } from "react";
import { ArrowUpRight, Bookmark, Copy, History, Pencil, Search, Trash2, Palette, Blend, Plus } from "lucide-react";
import type { SavedCreation } from "@/types";
import { gradientCss } from "@/lib/gradient";

export default function Collection({ items, history = false, onLoad, onRename, onDuplicate, onDelete, onCreate }: { items: SavedCreation[]; history?: boolean; onLoad: (item: SavedCreation) => void; onRename: (item: SavedCreation) => void; onDuplicate: (item: SavedCreation) => void; onDelete: (item: SavedCreation) => void; onCreate: () => void }) {
  const [filter, setFilter] = useState("all");
  const [query, setQuery] = useState("");
  const filtered = items.filter(item => (filter === "all" || item.kind === filter) && item.name.toLowerCase().includes(query.toLowerCase()));
  return <section className="collection"><div className="page-intro"><span className="eyebrow">{history ? "THE CREATIVE PROCESS" : "YOUR PERSONAL COLOR LIBRARY"}</span><h1>{history ? "Every happy accident." : "The keepers."}<span className="accent-dot">.</span></h1><p>{history ? "Your 30 most recent creations. Pick up any thread of inspiration." : "A little collection of colors you’ll come back to."}</p></div>
    <div className="collection-toolbar"><div className="segmented" aria-label="Filter creations">{[{ id: "all", label: "All creations" }, { id: "palette", label: "Palettes" }, { id: "gradient", label: "Gradients" }].map(tab => <button key={tab.id} className={filter === tab.id ? "active" : ""} aria-pressed={filter === tab.id} onClick={() => setFilter(tab.id)}>{tab.label}</button>)}</div><label className="search-field"><Search size={16} /><input placeholder="Find a creation…" aria-label="Search creations" value={query} onChange={e => setQuery(e.target.value)} /><span className="result-count">{filtered.length}</span></label></div>
    {filtered.length ? <div className="collection-grid">{filtered.map(item => <article className="creation-card" key={item.id}><button className="creation-preview" aria-label={`Load ${item.name}`} onClick={() => onLoad(item)} style={item.kind === "gradient" ? { background: gradientCss(item.gradient) } : undefined}>{item.kind === "palette" && item.palette.colors.map(color => <span key={color.id} style={{ background: color.hex }} />)}<span className="creation-open"><ArrowUpRight size={20} /></span></button><div className="creation-body"><span className="creation-type">{item.kind === "palette" ? <Palette size={12} /> : <Blend size={12} />}{item.kind === "palette" ? `${item.palette.colors.length} color palette` : `${item.gradient.type} gradient`}</span><h3><button onClick={() => onLoad(item)}>{item.name}</button></h3><div className="creation-bottom"><time dateTime={item.createdAt}>{new Date(item.createdAt).toLocaleDateString(undefined, { month: "short", day: "numeric" })}</time><div>{!history && <button className="icon-button" title="Rename" aria-label={`Rename ${item.name}`} onClick={() => onRename(item)}><Pencil size={14} /></button>}<button className="icon-button" title={history ? "Save to collection" : "Duplicate"} aria-label={`${history ? "Save" : "Duplicate"} ${item.name}`} onClick={() => onDuplicate(item)}>{history ? <Bookmark size={14} /> : <Copy size={14} />}</button>{!history && <button className="icon-button danger-hover" title="Delete" aria-label={`Delete ${item.name}`} onClick={() => onDelete(item)}><Trash2 size={14} /></button>}</div></div></div></article>)}</div> : <div className="empty-state"><div className="empty-art"><span /><span /><span />{history ? <History size={29} /> : <Bookmark size={29} />}</div><h2>{query || filter !== "all" ? "No matching creations." : history ? "The best part is starting." : "Your next favorite is out there."}</h2><p>{query || filter !== "all" ? "Try another name or filter to find your colors." : history ? "Generate a palette or forge a gradient. Your recent designs will appear here." : "No creations saved yet. Make something you love, then give it a home here."}</p><button className="button button-primary" onClick={query || filter !== "all" ? () => { setQuery(""); setFilter("all"); } : onCreate}>{query || filter !== "all" ? <Search size={16} /> : <Plus size={16} />}{query || filter !== "all" ? "Reset filters" : "Create your first palette"}</button></div>}
    <div className="collection-footnote"><span className="status-dot" />{history ? "Recent designs are kept on this device. Save a favorite to keep it in your collection." : "Your collection lives in this browser. Export your favorites for a lasting backup."}</div>
  </section>;
}
